version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=connectly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - connectly_network

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - connectly_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  connectly_network:
    driver: bridge