version: '3.8'

services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py create_superuser && python manage.py collectstatic --noinput && /usr/local/bin/gunicorn --bind 0.0.0.0:8000 connectly.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    networks:
      - default

volumes:
  static_volume:
  media_volume:

networks:
  default:
    external: true
    name: connectly_network 