version: "3.8"

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=connectly
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - connectly_network

  web:
    build: .
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - .:/app # Mount the current directory for development
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1 # Enable real-time logging
      - DJANGO_SETTINGS_MODULE=connectly.settings # Ensure Django settings are loaded
    depends_on:
      - db
    restart: always
    networks:
      - connectly_network
    command: python manage.py runserver 0.0.0.0:8000 # Use Django's development server

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  connectly_network:
    driver: bridge
